--- #YAML:1.0
name:               Net-Evernote-Simple
version:            0.03
abstract:           Simple interface to the Evernote API
author:
    - Mike Schilli <cpan@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:     0.22
    Log::Log4perl:  1
    Thrift:         0.6
    YAML:           0.71
resources:
    repository:  http://github.com/mschilli/net-evernote-simple.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
